### ISSUE TITLE
Ring fails after a few seconds of execution

### ISSUE THREAD

**Issue by sagaardu** [JK-Rolling/DuinoCoinI2C_RPI#3]
Hello, I have connected several arduino mini pro following the connection scheme described in this project.

After installing everything I see that the 5 devices are recognized via I2C from raspberry 2:

     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          03 04 05 06 07 -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

for each arduino I changed the value as recommended from

#define DEV_INDEX 1

I left it like this:
arduino 1 -> value 1
arduino -> value 2
arduino3 -> value 3
arduino4 -> value 4
arduino5 -> value 5

however even though everything seems to start fine after a few seconds the script fails giving the following error

```
sudo python3 ./AVR_Miner_RPI.py

12:20:28  net0  Searching for the fastest node to connect to
12:20:29  net0  Connected to master Duino-Coin server (v2.7)
12:20:29  net0  MOTD: Welcome to the null duino pool!
                Pool worker limit: 50
12:20:29  sys3  AVR mining thread is starting using DUCO-S1A algorithm (3)
12:20:33  avr3   Rejected 0/1 (0%)  02.4s  228 H/s  diff 6  ping 68ms
12:20:45  avr3   Accepted 1/2 (50%)  06.5s  228 H/s  diff 16  ping 77ms
12:20:49  avr3   Accepted 2/3 (67%)  04.0s  228 H/s  diff 16  ping 89ms
12:20:52  avr3   Accepted 3/4 (75%)  02.9s  228 H/s  diff 16  ping 81ms
12:20:54  avr3   Accepted 4/5 (80%)  01.6s  228 H/s  diff 16  ping 112ms
12:21:00  avr3   Accepted 5/6 (83%)  05.4s  228 H/s  diff 16  ping 114ms
12:21:06  avr3   Accepted 6/7 (86%)  05.8s  228 H/s  diff 16  ping 116ms
12:21:07  avr3   Accepted 7/8 (88%)  00.8s  228 H/s  diff 16  ping 113ms
12:21:08  avr3   Accepted 8/9 (89%)  01.0s  227 H/s  diff 16  ping 118ms
12:21:09  avr3   Accepted 9/10 (90%)  00.3s  227 H/s  diff 16  ping 113ms
12:21:13  avr3   Accepted 10/11 (91%)  03.5s  227 H/s  diff 16  ping 114ms
12:21:16  avr3   Accepted 11/12 (92%)  03.3s  227 H/s  diff 16  ping 112ms
12:21:23  avr3   Accepted 12/13 (92%)  06.4s  227 H/s  diff 16  ping 109ms
12:21:23  avr3   Accepted 13/14 (93%)  00.1s  223 H/s  diff 16  ping 111ms
12:21:29  avr3   Accepted 14/15 (93%)  05.7s  224 H/s  diff 16  ping 97ms
12:21:29  net0  POOL_INFO: Welcome to the null duino pool!
                Pool worker limit: 50
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./AVR_Miner_RPI.py", line 893, in mine_avr
    shares[2], hashrate, uptime)
  File "./AVR_Miner_RPI.py", line 915, in periodic_report
    + get_string('total_mining_time') + str(uptime), "success")
  File "./AVR_Miner_RPI.py", line 606, in pretty_print
    + Back.RESET + " " + fg_color + msg.strip())
  File "/usr/local/lib/python3.6/site-packages/colorama/ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "/usr/local/lib/python3.6/site-packages/colorama/ansitowin32.py", line 164, in write
    self.wrapped.write(text)
  File "/usr/local/lib/python3.6/site-packages/colorama/ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "/usr/local/lib/python3.6/site-packages/colorama/ansitowin32.py", line 164, in write
    self.wrapped.write(text)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2016' in position 88: ordinal not in range(128)
```

what`s the problem?

**Comment by JK-Rolling** [comment]
the Python version needs to be 3.7 and above. Yours is using 3.6. The version I'm using is 3.7.3. try `sudo apt update && sudo apt upgrade -y`. check the version using `python3 -V` again.
